services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nyaminet
      MYSQL_USER: nyami
      MYSQL_PASSWORD: nyami
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  db_data:




